import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/providers/Providers";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Second BD",
  description: "Generated by Second BD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.className} antialiased`}
        >
          <Navbar />
          <Toaster richColors position="top-center" />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
